update scATAC

diff --git a/bin/scATAC b/bin/scATAC
--- a/bin/scATAC
+++ b/bin/scATAC
@@ -5,6 +5,9 @@ command -v bwa >/dev/null 2>&1 || { echo >&2 "scATAC requires bwa but it is not 
 command -v samtools >/dev/null 2>&1 || { echo >&2 "scATAC requires samtools but it is not installed. Aborting."; exit 1; }
 command -v java >/dev/null 2>&1 || { echo >&2 "scATAC requires java but it is not installed. Aborting."; exit 1; }
 command -v scATAC_barcode_err_correct >/dev/null 2>&1 || { echo >&2 "scATAC requires scATAC_barcode_err_correct but it is not installed. Aborting."; exit 1; }
+command -v scATAC_decell >/dev/null 2>&1 || { echo >&2 "scATAC requires scATAC_decell but it is not installed. Aborting."; exit 1; }
+
+#scATAC_rm_cell_with_low_cov='/oasis/tscc/scratch/r3fang/collaboration/Seb_04_26_2016/Mixtures_published_download/HL60_GM12878/scATAC_rm_cell_with_low_cov.py'
 
 # PART II usage info
 usage(){
@@ -66,12 +69,23 @@ do
 	esac
 done
 
+echo 
+echo THREADS=$THREADS
+echo FASTQ1=$FASTQ1
+echo FASTQ2=$FASTQ2
+echo BARCODE_DIR=$BARCODE_DIR
+echo MAX_BARCODE_MISMATCH=$MAX_BARCODE_MISMATCH
+echo MARK_DUPLICATE=$MARK_DUPLICATE
+echo PREFIX=$PREFIX
+echo GENOME=$GENOME
+echo MIN_READ=$MIN_READ
+echo 
+
 if [ $# -lt 10 ] ; then
    usage
    echo "error: too few arguments"
    exit 1
 fi
-
 
 # check if files exist
 if [ ! -f $FASTQ1 ]; then
@@ -101,6 +115,7 @@ fi
 
 if [ ! -f $BARCODE_DIR/r7 ]; then
 	usage
+	echo $BARCODE_DIR/r7
     echo "error: '$BARCODE_DIR/r7' not exists.";
 	exit 1
 fi
@@ -140,10 +155,6 @@ if ! [[ $MIN_READ =~ $re ]] ; then
    exit 1
 fi
 
-#scATAC_decell='/oasis/tscc/scratch/r3fang/collaboration/Seb_04_26_2016/Mixtures_published_download/HL60_GM12878/scATAC_decell.py'
-#mark_duplcate='/oasis/tscc/scratch/r3fang/github/Hicmap_Ren/Picard/MarkDuplicates.jar'
-#scATAC_rm_cell_with_low_cov='/oasis/tscc/scratch/r3fang/collaboration/Seb_04_26_2016/Mixtures_published_download/HL60_GM12878/scATAC_rm_cell_with_low_cov.py'
-
 echo 'Step 1. map and filter reads with poor mappability'
 bwa mem -M -t 5 $GENOME $FASTQ1 $FASTQ2 \
 | samtools view -q 10 -bS - > $PREFIX.umap.bam
@@ -156,42 +167,39 @@ samtools view -h $PREFIX.umap.bam \
 echo 'Step 3. sort reads based on name'
 samtools sort -n -m 1G $PREFIX.umap.corrected.bam $PREFIX.umap.corrected.nsorted
 
-echo 'Step 4. seperate reads into each cell' 
+echo 'Step 4. split reads into each cell' 
+rm -r $PREFIX\_TMP # remove folder by force
 mkdir $PREFIX\_TMP # create a tmp folder
 samtools view $PREFIX.umap.corrected.nsorted.bam \
 | scATAC_decell $PREFIX\_TMP -
 
-#echo 'Step 5. remove PCR duplication for each cell'
-#samtools view -H $PREFIX.umap.corrected.nsorted.bam > $PREFIX.umap.corrected.nsorted.header
-#for line in `ls $TMP_FOLDER | grep .sam`
-#do
-#	barcode="${line%.*}"
-#	cat $PREFIX.umap.2mm.nsorted.header $TMP_FOLDER/$line | samtools view -bS - | samtools sort - $TMP_FOLDER/$barcode.sorted
-#	java -Xmx2G -jar $mark_duplcate INPUT=$TMP_FOLDER/$barcode.sorted.bam OUTPUT=$TMP_FOLDER/$barcode.sorted.filtered.bam ASSUME_SORTED=true \
-#		REMOVE_DUPLICATES=true VALIDATION_STRINGENCY=LENIENT METRICS_FILE=$TMP_FOLDER/metrics.$barcode.txt TMP_DIR=$TMP_FOLDER/$barcode\_tmp
-#	rm $TMP_FOLDER/$barcode.sorted.bam
-#	rm -r $TMP_FOLDER/$barcode\_tmp
-#done
-#
-#echo 'Step 6. merge cells'
-#samtools cat -o $PREFIX.umap.2mm.nsorted.nodup.bam $TMP_FOLDER/*.sorted.filtered.bam
-#
-#echo 'Step 7. remove intermedia files/folders'
-#rm $PREFIX.umap.2mm.nsorted.header
-#rm -r $TMP_FOLDER
-#
-#echo 'Step 8. sort by genomic coordinates'
-#samtools sort -m 1G $PREFIX.umap.2mm.nsorted.nodup.bam $PREFIX.umap.2mm.nsorted.nodup.gsorted
-#
-#echo 'Step 9. generate barcode frequency table'
-#samtools view $PREFIX.umap.2mm.bam \
-#| awk '{split($1,a,":"); print a[1]}' | sort | uniq -c | awk '{print $2, $1}' \
-#| sort -k2rn - > $PREFIX.umap.2mm.stat &
-#
-#samtools view $PREFIX.umap.2mm.nsorted.nodup.gsorted.bam \
-#| awk '{split($1,a,":"); print a[1]}' | sort | uniq -c | awk '{print $2, $1}' \
-#| sort -k2rn - > $PREFIX.umap.2mm.nsorted.nodup.gsorted.stat 
-#
+echo 'Step 5. remove PCR duplication for each cell'
+samtools view -H $PREFIX.umap.corrected.nsorted.bam > $PREFIX.umap.corrected.nsorted.header
+for line in `ls $PREFIX\_TMP | grep .sam`
+do
+	barcode="${line%.*}"
+	cat $PREFIX.umap.corrected.nsorted.header $PREFIX\_TMP/$line \
+	| samtools view -bS - \
+	| samtools sort - $PREFIX\_TMP/$barcode.sorted \
+	| java -Xmx2G -jar $MARK_DUPLICATE INPUT=$PREFIX\_TMP/$barcode.sorted.bam OUTPUT=$PREFIX\_TMP/$barcode.sorted.filtered.bam ASSUME_SORTED=true \
+		REMOVE_DUPLICATES=true VALIDATION_STRINGENCY=LENIENT METRICS_FILE=$PREFIX\_TMP/metrics.$barcode.txt TMP_DIR=$PREFIX\_TMP/$barcode\_tmp
+done
+
+echo 'Step 6. merge cells'
+samtools cat -o $PREFIX.umap.corrected.nsorted.nodup.bam $PREFIX\_TMP/*.sorted.filtered.bam
+
+echo 'Step 7. remove intermedia files/folders'
+rm $PREFIX.umap.2mm.nsorted.header
+rm -r $PREFIX\_TMP/
+
+echo 'Step 8. sort by genomic coordinates'
+samtools sort -m 1G $PREFIX.umap.corrected.nsorted.nodup.bam $PREFIX.umap.corrected.nsorted.nodup.gsorted
+
+echo 'Step 9. generate barcode frequency'
+samtools view $PREFIX.umap.corrected.nsorted.nodup.gsorted.bam \
+| awk '{split($1,a,":"); print a[1]}' | sort | uniq -c | awk '{print $2, $1}' \
+| sort -k2rn - > $PREFIX.umap.corrected.nsorted.nodup.gsorted.stat 
+
 #echo 'Step 10. filter cells with low reads (less than 500 reads)'
 #samtools view -h $PREFIX.umap.2mm.nsorted.nodup.gsorted.bam \
 #| python $scATAC_rm_cell_with_low_cov 500 $PREFIX.umap.2mm.nsorted.nodup.gsorted.stat - \
